# Generated by Django 6.1 on 2026-09-16 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_invoice_amount_paid_alter_invoice_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('WALLET', 'Wallet'), ('CHAPA', 'Chapa'), ('TELEBIRR', 'Telebirr')], default='DIRECT', max_length=50),
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('CHAPA', 'Chapa'), ('TELEBIRR', 'Telebirr')], default='CHAPA', max_length=20)),
                ('purpose', models.CharField(choices=[('INVOICE_PAYMENT', 'Invoice Payment'), ('WALLET_DEPOSIT', 'Wallet Deposit')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_transactions', to='fees.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
