# Generated by Django 6.1 on 2026-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method_gatewaytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='funding_source',
            field=models.CharField(blank=True, default='DIRECT', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_account',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('DIRECT', 'Direct Bank Transfer'), ('WALLET', 'Digital Wallet'), ('CBE', 'Commercial Bank of Ethiopia (CBE)'), ('TELEBIRR', 'Telebirr'), ('BOA', 'Bank of Abyssinia (BoA)'), ('AWASH', 'Awash Bank'), ('DASHEN', 'Dashen Bank'), ('COOP', 'Cooperative Bank of Oromia'), ('CARD', 'Debit/Credit Card (Visa/Mastercard)'), ('CHAPA', 'Chapa Online Gateway')], default='DIRECT', max_length=50),
        ),
    ]
