# Generated by Django 6.1 on 2026-10-01 18:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_invoice_amount_paid_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.invoice')),
            ],
            options={
                'ordering': ['installment_number'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'installment_number'), name='unique_invoice_installment')],
            },
        ),
    ]
