# Generated by Django 6.1 on 2026-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='funding_source',
            field=models.CharField(blank=True, default='DIRECT', max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source_account',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
