# Generated by Django 6.1 on 2026-10-01 18:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallettransaction_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='auto_pay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10),
        ),
    ]
